name: Build and Deploy (Chinese Reader API)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    name: Build and Push Image
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    env:
      IMAGE: ghcr.io/calebkey121/chinese-reader-api:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE }}

  deploy:
    name: Deploy on athens
    runs-on: self-hosted
    needs: build

    steps:
      - name: Deploy container
        run: bash /home/caleb/chinese_reader/deploy.sh
